### ISSUE TITLE
Validators clean up todo list

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#882]
- [x] in place of penalty ranking, add stake status "Staked, Cool Down, Unstaked"
- [x] in the kebab menu of Hotspots and Validators, add "Copy Owner Address"
- [x] on tap of the little pills above the validator name, using the "needs attention" component, show what each pill means.
<img width="201" alt="image" src="https://user-images.githubusercontent.com/19331274/129271602-73802e85-4206-40a8-8766-4b27a585fb5a.png">

"Validator Version"
"Blocks since the last heartbeat transaction"
"Penalty Score"

- [x] add icons next to search results to indicate if it's a validator or hotspot
- [x] add introductory text in CG view. make sure to use the consensus group chain var
<img width="271" alt="image" src="https://user-images.githubusercontent.com/19331274/129271808-8e6ed4d0-471f-4cd4-a53e-aab89067d3e9.png">

**Comment by cokes518** [comment]
nice stuff
